version: "5"
services:
  music-downloader:
    build: .
    volumes:
      - ~/Music/BeatHarvest:/downloads
      # - ~/Developer/BeatHarvest/backend/.env:/app/BeatHarvest/.env
    environment:
      - TZ=UTC # Set your timezone
    restart: unless-stopped
